/**
 * Impact Comment Formatter
 * 
 * Formats the analysis result into a GitHub PR comment
 * that creates the "never seen this before" moment.
 */

import { SymbolImpact, ArchitecturalViolation, ProcessImpact, AnalysisResult } from "./types.js";


/**
 * Format the analysis result into a GitHub PR comment
 */
export function formatImpactComment(analysis: AnalysisResult): string {
  const { prNumber, changedFiles, changedSymbols, affectedProcesses, violations, riskLevel, summary } = analysis;
  
  // Risk level header
  const riskEmoji = {
    low: '✅',
    medium: '🔶',
    high: '⚠️',
    critical: '🚨',
  };
  
  const riskLabel = {
    low: 'LOW RISK',
    medium: 'MEDIUM RISK',
    high: 'HIGH RISK',
    critical: 'CRITICAL RISK',
  };
  
  let md = `## ${riskEmoji[riskLevel]} CodeCortex Impact Analysis\n\n`;
  md += `### ${riskLabel[riskLevel]}\n\n`;
  
  // Summary stats
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Changed Files | ${changedFiles} |\n`;
  md += `| Modified Symbols | ${changedSymbols.length} |\n`;
  md += `| Affected Processes | ${affectedProcesses.length} |\n`;
  md += `| Architectural Violations | ${violations.length} |\n\n`;
  
  // Summary text
  md += `### 📊 Summary\n\n`;
  md += `${summary}\n\n`;
  
  // Critical symbols section
  const criticalSymbols = changedSymbols.filter(s => s.risk === 'critical');
  if (criticalSymbols.length > 0) {
    md += `### 🚨 Critical Symbols Modified\n\n`;
    md += `These are highly connected nodes in your system. Changes here have cascading effects:\n\n`;
    
    for (const symbol of criticalSymbols) {
      md += `- **\`${symbol.name}\`** (${symbol.type})\n`;
      md += `  - 📍 File: \`${symbol.filePath}\`\n`;
      md += `  - 👥 Callers: ${symbol.callers}\n`;
      md += `  - 📊 Depth: ${symbol.depth}\n\n`;
    }
  }
  
  // High-risk symbols section
  const highSymbols = changedSymbols.filter(s => s.risk === 'high');
  if (highSymbols.length > 0) {
    md += `### ⚠️ High-Risk Symbols\n\n`;
    md += `These symbols have significant downstream impact:\n\n`;
    
    for (const symbol of highSymbols) {
      md += `- **\`${symbol.name}\`** (${symbol.type})\n`;
      md += `  - 📍 File: \`${symbol.filePath}\`\n`;
      md += `  - 👥 Callers: ${symbol.callers}\n\n`;
    }
  }
  
  // Architectural violations section
  if (violations.length > 0) {
    md += `### 🏗️ Architectural Violations\n\n`;
    md += `The following violations of your architectural rules were detected:\n\n`;
    
    for (const violation of violations) {
      md += `- **${violation.rule}**\n`;
      md += `  - ${violation.description}\n`;
      md += `  - 📍 Locations: ${violation.locations.map(l => `\`${l}\``).join(', ')}\n\n`;
    }
  }
  
  // Affected processes section
  if (affectedProcesses.length > 0) {
    md += `### 💥 Blast Radius (Affected Processes)\n\n`;
    md += `The following end-to-end execution flows trace through your modified code and should be manually tested:\n\n`;
    
    for (const proc of affectedProcesses) {
      md += `<details><summary>\`${proc.name}\`</summary>\n\n`;
      md += `- **Type:** ${proc.type}\n`;
      md += `- **Total Steps:** ${proc.stepCount}\n`;
      md += `- **Affected Steps:** ${proc.affectedSteps}\n\n`;
      md += `</details>\n\n`;
    }
  }
  
  // All changed symbols (collapsible)
  if (changedSymbols.length > 0) {
    md += `<details><summary>📋 All Changed Symbols (${changedSymbols.length})</summary>\n\n`;
    
    for (const symbol of changedSymbols) {
      const riskIcon = {
        low: '✅',
        medium: '🔶',
        high: '⚠️',
        critical: '🚨',
      };
      
      md += `- ${riskIcon[symbol.risk]} **\`${symbol.name}\`** (${symbol.type}) — ${symbol.callers} callers\n`;
    }
    
    md += `\n</details>\n\n`;
  }
  
  // Footer
  md += `---\n\n`;
  md += `*🤖 This analysis was generated by [CodeCortex](https://codecortex.dev) — the architectural memory your AI coding assistant doesn't have.*\n\n`;
  md += `<details><summary>ℹ️ How this works</summary>\n\n`;
  md += `CodeCortex analyzes your codebase's structural relationships to understand:\n`;
  md += `- Which symbols are highly connected (critical nodes)\n`;
  md += `- What execution flows trace through your changes\n`;
  md += `- Whether your changes violate architectural rules\n\n`;
  md += `This helps you catch structural issues before they reach code review.\n`;
  md += `</details>`;
  
  return md;
}

/**
 * Format a minimal comment for low-risk PRs
 */
export function formatMinimalComment(analysis: AnalysisResult): string {
  const { riskLevel, changedSymbols, violations } = analysis;
  
  if (riskLevel === 'low' && violations.length === 0) {
    return `## ✅ CodeCortex: Low Impact\n\nNo significant architectural impact detected. ${changedSymbols.length} symbol(s) modified.`;
  }
  
  return formatImpactComment(analysis);
}
