import fs from 'fs/promises';
import path from 'path';

import {
  getFilesWithExports,
  getAllFiles,
  getInterFileCallEdges,
  getAllProcesses,
  FileWithExports,
} from './graph-queries.js';

import { shouldIgnorePath } from '../../config/ignore-service.js';
import type { WikiGenerator, ModuleTreeNode, WikiMeta } from './generator.js';

/**
 * Builds a deterministic wiki purely from the knowledge graph's structure
 * without using an LLM. Groups files by directory and maps out edges.
 */
export class StructuralRenderer {
  constructor(private generator: WikiGenerator) {}

  async run(currentCommit: string): Promise<{ pagesGenerated: number; mode: 'full'; failedModules: string[] }> {
    let pagesGenerated = 0;

    // Phase 0: Gather structure
    this.generator['onProgress']('gather', 5, 'Querying structural graph data...');
    const filesWithExports = await getFilesWithExports();
    const allFiles = await getAllFiles();
    const callEdges = await getInterFileCallEdges();
    const processes = await getAllProcesses();

    const sourceFiles = allFiles.filter(f => !shouldIgnorePath(f));
    if (sourceFiles.length === 0) {
      throw new Error('No source files found in the knowledge graph. Nothing to document.');
    }

    const exportMap = new Map(filesWithExports.map(f => [f.filePath, f]));
    const enrichedFiles: FileWithExports[] = sourceFiles.map(fp => {
      return exportMap.get(fp) || { filePath: fp, symbols: [] };
    });

    this.generator['onProgress']('group', 15, `Grouping ${sourceFiles.length} files by directory...`);

    // Group files by top-level directory (or second-level if too broad)
    const moduleGroups = new Map<string, string[]>();
    for (const f of sourceFiles) {
      const parts = f.split('/');
      let groupName = 'root';
      if (parts.length > 1) {
        // Group by the first folder, e.g., "src" or "packages/core"
        groupName = parts.length > 2 && parts[0] === 'packages' 
          ? `${parts[0]}/${parts[1]}` 
          : parts[0];
      }
      const existing = moduleGroups.get(groupName) || [];
      existing.push(f);
      moduleGroups.set(groupName, existing);
    }

    const moduleTree: ModuleTreeNode[] = [];
    for (const [name, files] of moduleGroups.entries()) {
      moduleTree.push({
        name,
        slug: name.replace(/[^a-zA-Z0-9-]/g, '-'),
        files,
      });
    }

    this.generator['onProgress']('modules', 30, `Generating markdown for ${moduleTree.length} modules...`);

    // Write module pages
    let modulesProcessed = 0;
    for (const mod of moduleTree) {
      const pagePath = path.join(this.generator['wikiDir'], `${mod.slug}.md`);
      const modFiles = enrichedFiles.filter(f => mod.files.includes(f.filePath));
      
      let md = `# Module: ${mod.name}\n\n`;
      md += `> Automatically generated structural overview.\n\n`;

      md += `## Files & Exports\n\n`;
      for (const f of modFiles) {
        md += `### \`${f.filePath}\`\n`;
        if (f.symbols.length > 0) {
          md += `**Exports:**\n`;
          for (const sym of f.symbols) {
            md += `- \`${sym.type}\` **${sym.name}**\n`;
          }
        } else {
          md += `*(No exported symbols)*\n`;
        }
        md += `\n`;
      }

      const modCallEdges = callEdges.filter(e => mod.files.includes(e.fromFile) || mod.files.includes(e.toFile));
      if (modCallEdges.length > 0) {
        md += `## Call Edges (Inter-file dependencies)\n\n`;
        const edgeMap = new Map<string, string[]>();
        for (const e of modCallEdges) {
          const key = `\`${e.fromFile}\` -> \`${e.toFile}\``;
          const val = edgeMap.get(key) || [];
          val.push(`${e.fromName}() \u2192 ${e.toName}()`);
          edgeMap.set(key, val);
        }
        for (const [key, callList] of edgeMap.entries()) {
          md += `- **${key}**\n`;
          for (const c of new Set(callList)) md += `  - ${c}\n`;
        }
        md += `\n`;
      }

      await fs.writeFile(pagePath, md, 'utf-8');
      pagesGenerated++;
      modulesProcessed++;
      
      const percent = 30 + Math.round((modulesProcessed / moduleTree.length) * 55);
      this.generator['onProgress']('modules', percent, `${modulesProcessed}/${moduleTree.length} modules (${mod.name})`);
    }

    // Write Overview Page
    this.generator['onProgress']('overview', 90, 'Generating Main Overview...');
    
    let overviewMd = `# Repository Overview\n\n`;
    overviewMd += `> Structural Wiki Generated by CodeCortex.\n\n`;
    
    overviewMd += `## Modules\n\n`;
    for (const mod of moduleTree) {
      overviewMd += `- [**${mod.name}**](${mod.slug}.md) (${mod.files.length} files)\n`;
    }
    overviewMd += `\n`;

    if (processes.length > 0) {
      overviewMd += `## Execution Flows\n\n`;
      for (const p of processes) {
        overviewMd += `### Flow: ${p.label || p.id}\n`;
        overviewMd += `- **Type**: ${p.type || 'Unknown'}\n`;
        if (p.stepCount) {
          overviewMd += `- **Total Steps**: ${p.stepCount}\n`;
        }
        overviewMd += `\n`;
      }
    }

    await fs.writeFile(path.join(this.generator['wikiDir'], 'overview.md'), overviewMd, 'utf-8');
    pagesGenerated++;

    const wikiMeta: WikiMeta = {
      fromCommit: currentCommit,
      generatedAt: new Date().toISOString(),
      model: 'structural-free',
      moduleTree,
      moduleFiles: Object.fromEntries(moduleTree.map(m => [m.name, m.files])),
    };
    await fs.writeFile(
      path.join(this.generator['wikiDir'], 'meta.json'),
      JSON.stringify(wikiMeta, null, 2)
    );

    return { pagesGenerated, mode: 'full', failedModules: [] };
  }
}
